'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Gift,LockKeyhole,CarFront,PackageOpen,Sparkles,LoaderCircle,Clock,ScanLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import QrPass from './qr-pass';
const stations=[{name:'試駕體驗',en:'THE DRIVE',icon:CarFront,desc:'握上方向盤，感受每一次從容前行。',steps:['依工作人員引導，進行現場試駕','完成指定體驗，請工作人員核實']},{name:'後廂收納挑戰',en:'THE SPACE',icon:PackageOpen,desc:'生活有多少想像，空間就有多少可能。',steps:['依現場規則，挑選玩偶與指定物品','將物品放入後車廂，完成收納挑戰']},{name:'仰望車頂光影',en:'THE VIEW',icon:Sparkles,desc:'坐進車內，換個角度探索。',steps:['依現場工作人員引導入座','欣賞車頂特效，完成體驗']},...Array.from({length:3},(_,i)=>({name:`關卡 0${i+4}`,en:'COMING SOON',icon:LockKeyhole,desc:'更多體驗，敬請期待。',steps:[]}))];
type State={id:string;stamps:number[];redeemedAt:string|null;claimCode:string};
export default function Experience(){
 const [view,setView]=useState('welcome'),[selected,setSelected]=useState(0),[state,setState]=useState<State|null>(null),[error,setError]=useState('');
 const count=state?.stamps.length??0;
 function go(v:string){setError('');setView(v);window.scrollTo({top:0,behavior:'instant'});}
 async function refresh(){const r=await fetch('/api/event',{cache:'no-store'});const d=await r.json() as State & {error?:string};if(!r.ok)throw Error(d.error || '暫時無法連線');setState(d);return d;}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!['reward','verify'].includes(view))return;let active=true;const timer=setInterval(()=>{refresh().then(data=>{if(active&&view==='verify'&&data.stamps.includes(selected+1))go('success')}).catch(e=>{if(active)setError(e.message)});},2000);return()=>{active=false;clearInterval(timer)}},[view,selected]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:'view_stamp_passport',description:'Open stamp directory and read server-saved progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');const data=await refresh();go('passport');return {completed:data.stamps,redeemed:!!data.redeemedAt};}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[]);
 const S=stations[selected];
 return <div className="site-shell"><aside className="desktop-note"><p>Mercedes-Benz</p><h2>探索，由此啟程。</h2><span>HUASHAN · 11.19 – 11.22</span><div className="side-line"/><p className="side-small">新車探索體驗<br/>六站探索，三章成禮。</p><a href="/staff">工作人員入口 <ArrowRight size={16}/></a></aside><main className={`phone-app screen-${view}`}>
 {view==='welcome'? <><div className="hero-photo"/><header className="welcome-brand"><Brand large/></header><section className="welcome-copy"><h1>探索，由此啟程</h1></section><div className="welcome-bottom"><p className="welcome-subtitle">新車探索體驗</p><p className="event-date">11.19 – 11.22 <span>華山</span></p><Button className="primary" onClick={()=>go('intro')}>開始探索 <ArrowRight/></Button><p className="concept-note">活動視覺提案</p></div></>:<>
 <header className="app-header">{['station','verify','success'].includes(view)?<button aria-label="返回" className="icon-button" onClick={()=>go(view==='verify'?'station':'passport')}><ArrowLeft size={21}/></button>:<span className="header-label"/>}<Brand/><span className="header-date"/></header>
 <div className="page-content" key={view}>
 {view==='intro'&&<><h1>六站探索，三章成禮</h1><p className="lead">完成任意 3 個關卡，即可兌換精美好禮。</p><div className="intro-photo"/><div className="steps">{[['選擇關卡','瀏覽六大體驗，自由安排順序。'],['現場體驗','完成挑戰，出示驗證碼給工作人員。'],['集章兌禮','集滿 3 章，至服務台領取好禮。']].map(([title,desc],i)=><div className="step" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div><Button className="primary" onClick={()=>go('passport')}>查看探索關卡 <ArrowRight/></Button></>}
 {view==='passport'&&<><div className="title-line"><span className="small-id">{state?`訪客 ${state.id.slice(0,6).toUpperCase()}`:'載入中'}</span></div><h1>我的探索護照</h1><div className="progress-area"><div className="count"><strong>{count}</strong><span>/ 3</span></div><p>{count>=3?'三章集齊，您的禮遇已開啟':`再集 ${3-count} 章，即可兌禮`}</p><Stamps count={count}/></div><div className="station-grid">{stations.map((s,i)=>{const done=state?.stamps.includes(i+1);return <button className={`station-tile tile-${i} ${done?'done':''}`} key={s.name} disabled={i>=3} onClick={()=>{setSelected(i);go('station')}}><div className="tile-top"><span>0{i+1}</span>{done&&<Check size={18}/>}</div><div><h3>{s.name}</h3><p className="tile-status">{i>=3?'待公布':done?'已完成':'前往體驗'}{i<3&&!done&&<ArrowRight size={14}/>}</p></div></button>})}</div>{count>=3&&<Button className="primary" onClick={()=>go('reward')}>查看我的禮遇 <Gift/></Button>}</>}
 {view==='station'&&<><p className="eyebrow">EXPERIENCE 0{selected+1} / 06</p><img className="detail-photo" src={selected===2?"/roof.png":selected===1?"/trunk.png":"/interior.png"} alt={S.name+"示意"}/><h1>{S.name}</h1><p className="lead">{S.desc}</p><div className="steps">{S.steps.map((s,i)=><div className="step" key={s}><span>0{i+1}</span><p>{s}</p></div>)}</div><p className="muted">實際體驗內容依現場安排。</p><div className="verification-hint"><LockKeyhole size={20}/><p>體驗完成後，<br/>請由工作人員核實集章。</p></div><Button className="primary" disabled={!state} onClick={()=>go(state?.stamps.includes(selected+1)?'passport':'verify')}>{state?.stamps.includes(selected+1)?'本關已完成 · 返回集章':'出示通關驗證碼'}<ArrowRight/></Button></>}
 {view==='verify'&&<div className="verification-page"><p className="lead">關卡 0{selected+1} · {S.name}</p><h1>請工作人員掃碼</h1><p className="lead">完成現場體驗後，出示此畫面</p><QrPass station={selected+1}/><Clock className="waiting-clock" size={45} strokeWidth={1}/><h2>等待工作人員確認</h2><p className="lead">確認後將自動取得印章</p><Button variant="outline" className="return-button" onClick={()=>go('station')}>返回關卡</Button></div>}
 {view==='success'&&<div className="success-view"><p className="eyebrow">EXPERIENCE COMPLETED</p><div className="success-mark"><Check size={56} strokeWidth={1}/></div><h1>這一站，已收藏。</h1><p className="lead">{S.name} · 通關成功</p><Stamps count={count}/><p>{count>=3?'您已集滿 3 章，可以兌換活動好禮。':`已取得 ${count} 章，再探索 ${3-count} 站即可兌禮。`}</p><Button className="primary" onClick={()=>go(count>=3?'reward':'passport')}>{count>=3?'前往兌換好禮':'繼續探索'}<ArrowRight/></Button></div>}
 {view==='reward'&&<><h1>{state?.redeemedAt?'禮遇，已為您送上。':count>=3?'三章集齊，禮遇開啟':'每一次探索，\n更接近一份禮遇。'}</h1><Stamps count={count}/><div className="gift-photo"><img src="/gift.png" alt="精美活動好禮示意"/><span>禮物示意</span></div><h2 className="gift-title">精美活動好禮</h2>{state?.redeemedAt?<div className="reward-status"><Check/><h3>已完成領取</h3><p>{new Date(state.redeemedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}</p><p>感謝您的參與，期待再次相見。</p></div>:count>=3?<div className="reward-status"><p>請至服務台出示兌換碼，由工作人員核銷領取。</p><QrPass station={0}/><span className="eligible">尚未兌換</span></div>:<><p className="lead">目前已集 {count} 章，<br/>再完成 {3-count} 個關卡即可兌換。</p><Button className="primary" onClick={()=>go('passport')}>前往集章 <ArrowRight/></Button></>}<p className="reward-note">每位參加者限領一次<br/>實際贈品依現場公告</p></>}
 </div><nav className="bottom-nav" aria-label="主要導覽">{[['intro','活動'],['passport','集章'],['reward','禮遇']].map(([v,label])=><button key={v} aria-current={view===v?'page':undefined} className={(view===v||(v==='passport'&&['station','verify','success'].includes(view)))?'active':''} onClick={()=>go(v)}>{label}</button>)}</nav></>}
 {error&&<div className="error-notice" role="alert"><p>{error}</p>{!state&&<button onClick={()=>{setError('');refresh().catch(e=>setError(e.message))}}>重新載入</button>}</div>}
 </main></div>
}
function Brand({large=false}:{large?:boolean}){return <div className={`brand ${large?'large':''}`}><img src="/logo.png" alt="Mercedes-Benz 三芒星"/><span>Mercedes-Benz</span></div>}
function Stamps({count}:{count:number}){return <div className="stamps" aria-label={`已集 ${count} 章，共需 3 章`}>{[0,1,2].map(i=><span className={i<count?'filled':''} key={i}>{i<count?<Check size={23} strokeWidth={1.5}/>:null}</span>)}</div>}


