'use client';
import {useEffect,useRef,useState} from 'react';
import {BrowserQRCodeReader,IScannerControls} from '@zxing/browser';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import Stats from './stats';
import {ScanLine,Check} from 'lucide-react';
type Visitor={id:string;stamps:number[];redeemedAt:string|null;station:number;expiresAt:number};
const names=['禮物兌換','試駕體驗','後廂收納挑戰','仰望車頂光影'];
export default function Staff(){const [tab,setTab]=useState('scan');const [auth,setAuth]=useState(false),[loading,setLoading]=useState(true),[password,setPassword]=useState(''),[token,setToken]=useState(''),[visitor,setVisitor]=useState<Visitor|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[scanning,setScanning]=useState(false),[expired,setExpired]=useState(false);const video=useRef<HTMLVideoElement>(null),controls=useRef<IScannerControls|null>(null),cancelled=useRef(false);
 async function sync(){const r=await fetch('/api/staff',{cache:'no-store'}),d=await r.json() as {authenticated:boolean;error:string};if(!r.ok)throw Error(d.error);setAuth(d.authenticated);return d.authenticated;}
 async function inspect(value:string){setTab('scan');setBusy(true);setMessage('');setVisitor(null);setConfirmed(false);setToken(value);try{const r=await fetch('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'inspect',token:value})}),d=await r.json() as Visitor&{error:string};if(!r.ok)throw Error(d.error);setVisitor(d);setExpired(false);}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 function stop(){cancelled.current=true;controls.current?.stop();controls.current=null;setScanning(false);}
 useEffect(()=>{const read=()=>{const p=new URLSearchParams(window.location.hash.slice(1));return p.get('ticket')||''};const initial=read();setToken(initial);sync().then(ok=>{if(ok&&initial)inspect(initial)}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false));const hash=()=>{const t=read();if(t){setToken(t);sync().then(ok=>{if(ok)inspect(t)}).catch(()=>{})}};window.addEventListener('hashchange',hash);return()=>{window.removeEventListener('hashchange',hash);cancelled.current=true;controls.current?.stop()}},[]);
 useEffect(()=>{const timer=setInterval(()=>setExpired(!!visitor&&visitor.expiresAt<Date.now()),500);return()=>clearInterval(timer)},[visitor]);
 async function start(){setMessage('');setVisitor(null);setConfirmed(false);if(!window.isSecureContext){setMessage('相機需要 HTTPS 網址，請使用已部署的網站。');return}cancelled.current=false;setScanning(true);try{const reader=new BrowserQRCodeReader();const c=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}}},video.current!,async(result)=>{if(result&&!cancelled.current){stop();try{const url=new URL(result.getText());if(url.origin!==location.origin||url.pathname!=='/staff')throw Error('請掃描本活動的 QR Code');const t=new URLSearchParams(url.hash.slice(1)).get('ticket');if(!t)throw Error('無效 QR Code');await inspect(t);}catch(e){setMessage((e as Error).message)}}});if(cancelled.current)c.stop();else controls.current=c;}catch{stop();setMessage('無法開啟相機，請允許相機權限，或使用手機內建相機掃描。')}}
 async function act(action:string){setBusy(true);setMessage('');try{const r=await fetch('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,password,token,confirm:confirmed})}),d=await r.json() as Visitor&{error:string};if(!r.ok)throw Error(d.error);if(action==='login'){setPassword('');await sync();if(token)await inspect(token);}else if(action==='logout'){stop();setAuth(false);setVisitor(null);setToken('');history.replaceState(null,'','/staff');}else{setVisitor(d);setConfirmed(false);setMessage(d.station===0?'核銷成功，請交付禮物。':'通關完成，印章已送出。');}}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const done=!!visitor&&(visitor.station===0?!!visitor.redeemedAt:visitor.stamps.includes(visitor.station));
 return <main className="staff-wrap"><header><div className="brand"><img src="/logo.png" alt="Mercedes-Benz"/><span>Mercedes-Benz</span></div><a href="/">返回活動</a></header><span className="staff-badge">工作人員專用</span><h1>{auth&&tab==='stats'?'活動數據':visitor?'核實'+(visitor.station===0?'兌獎':'通關'):'掃描通關驗證碼'}</h1>{loading?<p>連線中…</p>:!auth?<form onSubmit={e=>{e.preventDefault();act('login')}}><p className="lead">登入後，掃描參加者手機上的 QR Code。</p><label htmlFor="staff-password">工作人員密碼</label><input id="staff-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><Button className="primary" disabled={busy||!password}>{busy?'登入中…':'登入'}</Button></form>:<><p className="muted">已登入 · 現場體驗服務</p><div className="staff-tabs" role="tablist" aria-label="後台功能"><button role="tab" aria-selected={tab==='scan'} onClick={()=>{setTab('scan');setMessage('')}}>掃碼核實</button><button role="tab" aria-selected={tab==='stats'} onClick={()=>{stop();setTab('stats');setMessage('')}}>活動數據</button></div>{tab==='stats'?<Stats/>:<><video ref={video} className={scanning?'scanner-video':'scanner-hidden'} muted playsInline/><div aria-live="polite">{scanning&&<><p>請將 QR Code 對準鏡頭</p><Button variant="outline" onClick={stop}>停止掃描</Button></>}</div>{visitor?<section className="staff-review"><dl><div><dt>參加者</dt><dd>訪客 {visitor.id.slice(0,6).toUpperCase()}</dd></div><div><dt>驗證項目</dt><dd>{visitor.station?`0${visitor.station} `:''}{names[visitor.station]}</dd></div><div><dt>目前集章</dt><dd>{visitor.stamps.length} / 3</dd></div></dl><img className="staff-photo" src={visitor.station===0?'/gift.png':visitor.station===3?'/roof.png':'/interior.png'} alt="活動體驗示意"/>{done?<p className="staff-message"><Check/> {visitor.station===0?'已完成領取':'此關已通關'}</p>:expired?<p role="alert">驗證碼已過期，請重新掃描參加者最新的碼。</p>:<><div className="confirm-line"><Checkbox id="confirm" checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><label htmlFor="confirm">{visitor.station===0?'已核對參加者，確認發放一份好禮':'已確認完成現場體驗'}</label></div><p className="muted">{visitor.station===0?'核銷後，同一份禮物無法再次領取。':'確認後將發送本關印章。'}</p><Button className="primary" disabled={!confirmed||busy||expired} onClick={()=>act('confirm')}>{visitor.station===0?'確認核銷並發放':'確認通關並蓋章'}</Button></>}</section>:!scanning&&<div className="scan-empty"><ScanLine size={80} strokeWidth={1}/><p>掃描後核對參加者與關卡，<br/>再確認通關或禮物發放。</p></div>}{!scanning&&<Button className={visitor?'secondary-action':'primary'} variant={visitor?'ghost':'default'} onClick={start} disabled={busy}>{visitor?'返回掃描下一位':'開啟相機掃描'}</Button>}</>}<Button variant="ghost" className="secondary-action" onClick={()=>act('logout')} disabled={busy}>登出工作人員</Button></>}{message&&<p className="staff-message" role="status">{message}</p>}</main>}
