'use client';
import {useEffect,useState} from 'react';
type Data={summary:Record<string,number>;stations:{station:number;count:number}[];daily:{day:string;joined:number;qualified:number;redeemed:number;stamps:number}[];records:{id:string;created_at:string;completed:number;stations:string;redeemed_at:string|null}[];updatedAt:string};
const names=['試駕體驗','後廂收納挑戰','仰望車頂光影','關卡 04','關卡 05','關卡 06'];
const time=(v:string)=>new Date(v).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});
export default function Stats(){
const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[exporting,setExporting]=useState(false);
useEffect(()=>{let live=true;const controller=new AbortController();async function load(){setBusy(true);try{const r=await fetch('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'stats',page}),signal:controller.signal});const d=await r.json() as Data & {error:string};if(!r.ok)throw Error(d.error);if(live){setData(d);setError('')}}catch(e){if(live){setData(null);setError((e as Error).message)}}finally{if(live)setBusy(false)}}load();const timer=setInterval(load,30000);return()=>{live=false;controller.abort();clearInterval(timer)}},[page,refresh]);
async function download(){setExporting(true);setError('');try{const r=await fetch('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'export'})});if(!r.ok){const d=await r.json() as Data & {error:string};throw Error(d.error)}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='賓士活動紀錄.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setExporting(false)}}
return <section className="stats-panel" aria-label="活動數據"><div className="stats-tools"><button disabled={busy} onClick={()=>setRefresh(x=>x+1)}>{busy?'更新中…':'重新整理'}</button><button disabled={exporting||!data} onClick={download}>{exporting?'匯出中…':'匯出 CSV'}</button></div>{error&&<p role="alert" className="staff-message">{error}</p>}{data&&<><p className="stats-time">每 30 秒更新 · {time(data.updatedAt)}</p><div className="stat-grid">{[
['網站訪客身分','participants','個','曾開啟活動頁面並建立紀錄的瀏覽器身分；包含尚未通關者。'],
['總體驗者','started','位','至少完成 1 關且經工作人員確認的參加者；同一身分只計 1 位。'],
['集滿三章／可兌禮','qualified','位','至少完成 3 個不同關卡的參加者；包含已領取及尚未領取者。'],
['已核銷禮物','redeemed','份','工作人員確認發放並核銷成功的數量；每個身分限領 1 份。'],
['達標尚未領取','pending','位','已集滿 3 章但尚未核銷的參加者，不包含未達標者。'],
['通關總次數','stamps','次','所有成功通關紀錄加總；同一身分完成不同關卡會分別計次。']
].map(([label,key,unit,description])=><div className="stat-value" key={key}><span>{label}</span><strong>{data.summary[key].toLocaleString()}<em className="stat-unit">{unit}</em></strong><p className="metric-description">{description}</p></div>)}</div><div className="metric-guide"><h3>如何閱讀這些數字</h3><p>網站訪客不等於體驗者：只開啟網頁、尚未完成任何一關，不會計入「總體驗者」。正在排隊或體驗中但尚未核實者，也不計入。</p><p>同一位完成 3 關，計為「1 位總體驗者、3 次通關、1 位達標者」。此為計算範例，並非額外活動資料。</p><p>達標者 = 已核銷者 + 達標尚未領取者。目前每人限領一份，因此核銷份數與核銷身分數相同。</p><p>「位」依瀏覽器身分去重，並非真人身分驗證。清除瀏覽資料或換裝置可能產生新身分。Demo 核銷只表示系統操作成功，不代表現場真的發出禮物。</p></div><p className="stats-note">以工作人員核銷成功計算實際兌換。免登入版本以瀏覽器識別，非不重複真人數。此 Demo 包含先前測試紀錄。</p><RedemptionChart summary={data.summary}/><h2>各關完成人數</h2><p className="stats-note">單位：位。同一身分在同一關只計一次；同一位完成多關，會分別出現在各關。各關人數相加等於通關總次數，不等於總體驗者。長條以目前最多人完成的關卡為比例基準，不代表完成率。</p><div className="station-stats">{names.map((name,i)=><div key={name}><span>0{i+1} {name}{i>=3?'（待開放）':''}</span><strong>{data.stations.find(s=>s.station===i+1)?.count??0} 位</strong><div className="station-bar-track" aria-hidden="true"><span style={{width:((data.stations.find(s=>s.station===i+1)?.count??0)/Math.max(1,...data.stations.map(s=>s.count))*100)+'%'}}/></div></div>)}</div><DailyChart daily={data.daily}/><h2>每日統計明細</h2><p className="stats-note">臺灣時間（UTC+8）。新增依首次建立身分日、通關依每關確認日、達標依首次完成第 3 關日、核銷依確認發放日計算。跨日兌禮會計在實際核銷日，因此單日核銷數可能高於當日新增或達標數。</p><div className="stats-table-scroll"><table><thead><tr><th>日期</th><th>新增身分（個）</th><th>通關（次）</th><th>新達標（位）</th><th>核銷（份）</th></tr></thead><tbody>{data.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.joined}</td><td>{d.stamps}</td><td>{d.qualified}</td><td>{d.redeemed}</td></tr>)}</tbody></table>{!data.daily.length&&<p>尚無活動資料</p>}</div><h2>參加者紀錄</h2><p className="stats-note">共 {data.summary.participants} 筆 · 每頁 50 筆 · 新到舊</p><div className="participant-records">{data.records.map(r=><article key={r.id}><p title={r.id}>訪客 {r.id.slice(0,8).toUpperCase()} <span>{r.completed} 章 · {r.redeemed_at?'已兌換':r.completed>=3?'待兌換':'未達標'}</span></p><small>建立：{time(r.created_at)}<br/>完成關卡：{r.stations||'尚未通關'}{r.redeemed_at&&<><br/>兌換：{time(r.redeemed_at)}</>}</small></article>)}</div><div className="stats-tools"><button disabled={busy||page===0} onClick={()=>setPage(x=>x-1)}>上一頁</button><span>第 {page+1} 頁</span><button disabled={busy||(page+1)*50>=data.summary.participants} onClick={()=>setPage(x=>x+1)}>下一頁</button></div></>}</section>}


function RedemptionChart({summary}:{summary:Record<string,number>}){
 const rate=summary.qualified?Math.round(summary.redeemed/summary.qualified*100):0;
 return <section className="dashboard-chart"><h2>達標後兌禮進度</h2><div className="redemption-chart"><div className="redemption-ring"><svg viewBox="0 0 120 120" role="img" aria-label={summary.qualified?'達標者兌換率 '+rate+'%':'尚無達標者'}><circle cx="60" cy="60" r="49" fill="none" stroke="#30383e" strokeWidth="9"/><circle cx="60" cy="60" r="49" fill="none" stroke="#c3d9e7" strokeWidth="9" pathLength="100" strokeDasharray={rate+' 100'} transform="rotate(-90 60 60)"/></svg><div><strong>{summary.qualified?rate+'%':'—'}</strong><span>達標者兌換率</span></div></div><dl><div><dt><i className="chart-dot redeemed"/>已核銷</dt><dd>{summary.redeemed} 份</dd></div><div><dt><i className="chart-dot pending"/>尚待兌換</dt><dd>{summary.pending} 位</dd></div><div><dt>達標總數</dt><dd>{summary.qualified} 位</dd></div></dl></div><p className="stats-note">計算方式：已核銷者 ÷ 集滿三章者 × 100%，四捨五入至整數。未達標者不計入；100% 代表所有達標者都已核銷，不代表所有訪客都完成體驗。{!summary.qualified?'目前尚無達標紀錄。':''}</p></section>
}
function DailyChart({daily}:{daily:Data['daily']}){
 const days=[...daily].sort((a,b)=>a.day.localeCompare(b.day));const max=Math.max(1,...days.flatMap(d=>[d.joined,d.redeemed]));
 return <section className="dashboard-chart"><h2>每日參與與兌換</h2><p className="chart-legend"><span><i className="chart-dot redeemed"/>新增身分（個）</span><span><i className="chart-dot daily-redeemed"/>核銷禮物（份）</span></p>{days.length?<div className="daily-chart-scroll"><div className="daily-chart" style={{minWidth:Math.max(280,days.length*86)}}>{days.map(d=><div className="daily-column" key={d.day} aria-label={d.day+'：新增 '+d.joined+'，核銷 '+d.redeemed}><div className="daily-bars"><div><span>{d.joined}</span><i style={{height:d.joined/max*130}}/></div><div><span>{d.redeemed}</span><i style={{height:d.redeemed/max*130}}/></div></div><time dateTime={d.day}>{d.day.slice(5).replace('-','/')}</time></div>)}</div></div>:<p className="stats-note">尚無資料，活動開始後自動呈現。</p>}<p className="stats-note">依臺灣日期顯示有紀錄的日期；淺色為新增身分（個），深色為核銷禮物（份）。長條共用數量刻度，數值標示於上方；非兌換率，且不包含沒有任何紀錄的日期。</p></section>
}
