import fs from 'node:fs';
import path from 'node:path';
import {build} from 'vite';
import react from '@vitejs/plugin-react';
const root=process.cwd();
const temp=path.join(root,'.pages-src');
fs.mkdirSync(temp,{recursive:true});
let source=fs.readFileSync('app/experience.tsx','utf8');
source=source.replace("from './qr-pass'", "from '../app/qr-pass'");
source=source.replace("async function refresh(){", "async function refresh(){const preview={id:'PREVIEW',stamps:[],redeemedAt:null,claimCode:''};setState(preview);return preview; /*");
source=source.replace('setState(d);return d;}','setState(d);return d; */}');
source=source.replace('disabled={!state}', 'disabled={true}');
source=source.replace("'出示通關驗證碼'", "'QR 通關待連接後端'");
source=source.replaceAll('src="/', 'src="/Benz2026/').replaceAll('?"/', '?"/Benz2026/').replaceAll(':"/', ':"/Benz2026/');
source=source.replace('href="/staff"','href="#backend"');
fs.writeFileSync(path.join(temp,'experience.tsx'),source);
fs.writeFileSync(path.join(temp,'main.tsx'), 'import React from "react";import {createRoot} from "react-dom/client";import Experience from "./experience";import "../app/globals.css";createRoot(document.getElementById("root")!).render(<><div id="backend" style={{padding:"10px 16px",textAlign:"center",background:"#202428",color:"#ddd",fontSize:13}}>GitHub Pages 視覺預覽 · QR 蓋章與兌禮尚未連接後端</div><Experience/></>);');
fs.writeFileSync(path.join(temp,'index.html'),'<!doctype html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mercedes-Benz｜華山探索體驗</title></head><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>');
await build({configFile:false,root:temp,base:'/Benz2026/',publicDir:path.join(root,'public'),plugins:[react(),{name:'pages-assets',transform(code,id){if(id.endsWith('globals.css'))return code.replaceAll("url('/","url('/Benz2026/");}}],resolve:{alias:{'@':root}},build:{outDir:path.join(root,'docs'),emptyOutDir:true}});
fs.writeFileSync('docs/.nojekyll','');
